name: happyafterdisaster.com
favicon: null
layout_spectrum: 0.794762818608433
typography_spectrum: 0.5024772624019533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7874393262900412
  lightness: 0.49770064651966095
  saturation: 0.6741311142686754
  rhythmicContrast: 0.4852247789967805
purpose: []
